project_id = "anmvluvqdjjceinzgfnp"

[functions.gto-analysis]
verify_jwt = false

[functions.range-analysis]
verify_jwt = false

[functions.ev-analysis]
verify_jwt = false

[functions.equity-analysis]
verify_jwt = false

[functions.hand-analysis]
verify_jwt = false